# Generated by Django 5.2 on 2025-05-06 07:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("category", models.CharField(max_length=100)),
                (
                    "blog_body",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Content"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GellaryImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gellary/")),
                ("title", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="home_section/")),
                ("button_name", models.CharField(max_length=100)),
                ("redirect_to", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="SliderImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slider_images/")),
                ("title", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="UpcomingFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="upcoming_facilities/")),
                ("title", models.CharField(max_length=400)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=400)),
                ("expected_opening_date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "alternative_phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("button_name", models.CharField(max_length=100)),
                ("redirect_to", models.URLField()),
            ],
        ),
    ]
