# Generated by Django 5.2 on 2025-05-06 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ManageContent", "0004_accommodation_contactus_offers_alter_blog_blog_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accommodation",
            options={
                "verbose_name": "Accommodation",
                "verbose_name_plural": "Accommodations",
            },
        ),
        migrations.AlterModelOptions(
            name="contactus",
            options={"verbose_name": "Contact Us", "verbose_name_plural": "Contact Us"},
        ),
        migrations.AlterModelOptions(
            name="gellaryimages",
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.AlterModelOptions(
            name="homesection",
            options={
                "verbose_name": "Home Section",
                "verbose_name_plural": "Home Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="offers",
            options={"verbose_name": "Offer", "verbose_name_plural": "Offers"},
        ),
        migrations.AlterModelOptions(
            name="sliderimages",
            options={
                "verbose_name": "Slider Image",
                "verbose_name_plural": "Slider Images",
            },
        ),
        migrations.AlterModelOptions(
            name="upcomingfacilities",
            options={
                "verbose_name": "Upcoming Facility",
                "verbose_name_plural": "Upcoming Facilities",
            },
        ),
    ]
