# Generated by Django 5.2 on 2025-05-23 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ManageContent", "0006_aboutus_contactform_dining_blog_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutus",
            options={"verbose_name": "About Us", "verbose_name_plural": "About Us"},
        ),
        migrations.AlterModelOptions(
            name="dining",
            options={"verbose_name": "Dining", "verbose_name_plural": "Dining"},
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="button_name",
        ),
        migrations.RemoveField(
            model_name="aboutus",
            name="redirect_to",
        ),
    ]
