# Generated by Django 5.2 on 2025-05-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ManageContent", "0007_alter_aboutus_options_alter_dining_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dining",
            name="image",
            field=models.ImageField(upload_to="dining/"),
        ),
    ]
